name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "target/springboot-firebase-example-0.0.1-SNAPSHOT.jar"
          target: "target/liftu.jar"

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/liftu.jar
          remote: ${{ secrets.HOME_PATH }}/liftu.war
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
